# Generated by Django 6.1.1 on 2026-09-22 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('method', models.CharField(choices=[('web', 'Card / bank (Paynow checkout)'), ('ecocash', 'EcoCash')], default='web', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Awaiting payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('phone_number', models.CharField(blank=True, help_text='Used for EcoCash payments', max_length=20)),
                ('paynow_poll_url', models.URLField(blank=True)),
                ('paynow_redirect_url', models.URLField(blank=True)),
                ('paynow_transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
